name: Dependencies Example
on:
  workflow_dispatch:
jobs:
  dependancies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '15.x'
      - name: Verification
        run: ls -alhR
      
